### ISSUE TITLE
ack crashes perl after install

### ISSUE THREAD

**Issue by iainelder** [alanstevens/ChocoPackages#41]
I installed ack through cinst. It installed the Strawberry Perl dependency as well.

    $ cinst ack
    Chocolatey (v0.9.8.20) is installing ack and dependencies. By installing you accept the license for ack and each dependency you are installing.
    ______ StrawberryPerl v5.12.3.1 ______
    Downloading StrawberryPerl 64 bit (http://strawberry-perl.googlecode.com/files/strawberry-perl-5.12.3.0-64bit.msi) to C:\Users\iain\AppData\Local\Temp\chocolatey\StrawberryPerl\StrawberryPerlInstall.MSI.
    Installing StrawberryPerl...
    Elevating Permissions and running msiexec /i "C:\Users\iain\AppData\Local\Temp\chocolatey\StrawberryPerl\StrawberryPerlInstall.MSI" /qn INSTALLDIR="C:\strawberry" . This may take awhile, depending on the statements.
    StrawberryPerl has been installed.
    StrawberryPerl has finished succesfully! The chocolatey gods have answered your request!
    ______ ack v2.04 ______
    Finished installing 'ack' and dependencies - if errors not shown in console, none detected. Check log for errors if unsure.

Then I tried to run ack:
    
    $ ack

This error dialog appeared:

![The dialog says: "Perl interpreter has stopped working. A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available." The options are "Debug" and "Close program".](https://f.cloud.github.com/assets/5024311/2271393/b33f199e-9ef9-11e3-870a-519073fab692.png)

What can I do to fix this?

**Comment by alanstevens** [comment]
@iainelder I tried to repro this with no success. I've updated the packages for Strawberry Perl and Ack.

If you are able, please try the latest of both of these packages and see if the issue still occurs. If it does, reopen this ticket and I'll see if we can sort this out.

**Comment by iainelder** [comment]
I can confirm that this works today with Chocolatey 0.9.9.4.

**Comment by alanstevens** [comment]
Great, thanks. Followup if that changes.
