### ISSUE TITLE
(At least) two packages outdated

### ISSUE THREAD

**Issue by ComFreek** [alanstevens/ChocoPackages#62]
Hello @alanstevens,

happy new year!

Picasa and Foxit Reader are outdated. Concerning Foxit Reader I have already contacted the site admins, which will probably grant me write access to the Chocolatey package (I had sent you a mail using the 'Contact maintainers' formular on chocolatey.org). Locally I've already created an updated version of Foxit Reader, including the new logo they're using.
What do you think about a PR?

**Comment by mew1033** [comment]
Submit a PR. I can (and will, if it works) merge it. Hopefully you can get added as a maintainer on chocolatey.org.

**Comment by ComFreek** [comment]
Thanks, I will submit a PR after I hear back from the Chocolatey mod who is currently reviewing my other package submission. I've included an uninstaller, which reads the registry for the uninstaller file path, in both my new foxitreader package and that package. I am therefore waiting for the mod's opinion on the uninstaller script.

Do you have experience with automated packages? It would be nice to create such a package in order to prevent the scenario of an outdated package once again.
