### ISSUE TITLE
Ack is not listed

### ISSUE THREAD

**Issue by tylerszabo** [alanstevens/ChocoPackages#79]
I notice that the Ack (https://chocolatey.org/packages/ack) package isn't in this repo.

**Comment by railmeat** [comment]
Alan stopped maintaining his Choco Packages in 2014. I have a fork at
railmeat/ChocoPackages. Can you use that?

--
Matt Johnson

**Comment by tylerszabo** [comment]
Ah, awesome - thanks for linking to the sources. I've created a local version for my own use - but I thought other users could use a later version (it has bugfixes). I can submit a PR if you'd like. Would you be able to get the updated package into the Repo? (It looks like Alan is still the maintainer for the [main Chocolatey repo Ack](https://chocolatey.org/packages/ack))

I'm closing the issue ticket (as anything related the packages should be in [railmeat/ChocoPackages](https://github.com/railmeat/ChocoPackages)).

**Comment by tylerszabo** [comment]
I put in a request to become the maintainer - if you feel that you'd rather have the task ping me and I can rescind my request.

**Comment by railmeat** [comment]
I think it would be great if you took over maintaining Ack. I stopped maintaining any Chocolatey packages when I stopped using Windows.

I might be back to Windows since my MacBook Pro is breaking in mysterious ways, but that does not matter for this topic.
